// <auto-generated />
using DesignPatternConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignPatternConsoleApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesignPatternConsoleApp.DataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsAccountC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseOrganizationInstitutionC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealStateAgencyC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisteredTraingOrgTROC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RentalAgencyC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataModels");
                });
#pragma warning restore 612, 618
        }
    }
}
